name: Build Flutter Release

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

permissions:
  contents: write  # Allow creating and managing releases

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'  # Specify the Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Create GitHub Release and Upload APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: build/app/outputs/flutter-apk/app-release.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.0  # Replace with your desired version tag
        name: Release v1.0.0
        body: |
          ### What's New
          - Initial release of the APK.
